In [15]:
import tensorflow as tf
import numpy as np
print('TensorFlow version:', tf.__version__)

TensorFlow version: 1.5.0


## Представления тензоров

Способы задания матрицы

In [2]:
m1 = [[1.0, 2.0],
      [3.0, 4.0]]
m2 =  np.array([[1.0, 2.0],
                [3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0],
                  [3.0, 4.0]])

print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


Приведем все объекты к одному типу явным образом

In [3]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


Пример задания объектов через tf.constant (интерес представляет подробное описание объекта при его вызове)

In [4]:
tf.reset_default_graph()

In [5]:
m1 = tf.constant([[1., 2.]]) # 2x1
m2 = tf.constant([[1.],
                  [2,]]) #1x2
m3 = tf.constant([ [[1, 2],
                    [3, 4],
                    [5, 6]],
                   [[7, 8],
                    [9, 10],
                    [11, 12]]
                 ])
print(m1)
print(m2)
print(m3)

Tensor("Const:0", shape=(1, 2), dtype=float32)
Tensor("Const_1:0", shape=(2, 1), dtype=float32)
Tensor("Const_2:0", shape=(2, 3, 2), dtype=int32)


In [6]:
tf.ones([500, 500]) * 0.5

<tf.Tensor 'mul:0' shape=(500, 500) dtype=float32>

## Создание операторов 

Оператор изменения знака

In [7]:
tf.reset_default_graph()

In [8]:
x = tf.constant([[1., 2.]])
negMatrix = tf.negative(x)
print(negMatrix)

Tensor("Neg:0", shape=(1, 2), dtype=float32)


Пример гауссовой функции

<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/b77e66e0cfdc9859e63d68b5309bb794ad7cd1aa">

In [9]:
mean = 0.0
sigma = 1.0

gausDistr = (1.0/(sigma * tf.sqrt(2*np.pi)))*tf.exp(tf.negative(tf.pow((x - mean), 2))/(2 * tf.pow(sigma, 2)))

In [10]:
gausDistr

<tf.Tensor 'mul_2:0' shape=(1, 2) dtype=float32>

## Выполнене операторов во время сеанса

Явное использование tf.Sess

In [11]:
with tf.Session() as sess:
    neg_result = sess.run(negMatrix)
    distr_result = sess.run(gausDistr)
print(neg_result, distr_result)

[[-1. -2.]] [[0.24197073 0.05399097]]


Применение интерактивного режима отладки

In [12]:
sess = tf.InteractiveSession()

neg_result = negMatrix.eval()
distr_result = gausDistr.eval()
print(neg_result, distr_result)

sess.close() # Не забывать закрывать сессию!

[[-1. -2.]] [[0.24197073 0.05399097]]


Пример настройки конфигурации сеансов - вывод устрйоства, на котором будут производиться вычисления<br>
*Примечание - выводит логи в терминал, не в jupyter notebook*

In [13]:
tf.reset_default_graph()

x = tf.constant([[1., 2.]])
negMatrix = tf.negative(x)

with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    result = sess.run(negMatrix)
print(result)

[[-1. -2.]]


In [14]:
# (Const)/job:localhost/replica:0/task:0/device:CPU:0